"""empty message

Revision ID: 3f48f57c636f
Revises: 55de473075c6
Create Date: 2022-08-13 10:28:15.881873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f48f57c636f'
down_revision = '55de473075c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.drop_column('venues', 'talent_desc')
    op.drop_column('venues', 'web_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('web_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('talent_desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
