"""empty message

Revision ID: 5198a37255ec
Revises: 3f48f57c636f
Create Date: 2022-08-13 10:38:53.233121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5198a37255ec'
down_revision = '3f48f57c636f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.drop_column('artists', 'web_link')
    op.drop_column('artists', 'venue_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('venue_desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('web_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
