"""empty message

Revision ID: da0d0d2c90a6
Revises: 5198a37255ec
Create Date: 2022-08-13 10:52:55.875641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0d0d2c90a6'
down_revision = '5198a37255ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
